name: trip_genie
description: "A smart travel itinerary planner."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Services
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.0

  # User Authentication
  google_sign_in: ^6.2.1

  # State Management & Utilities
  provider: ^6.1.2
  intl: ^0.19.0
  google_generative_ai: ^0.4.0
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3

  # PDF Generation & File Management
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png