// File generated by FlutterFire CLI.
// DO NOT MODIFY.
//
// This file is generated from your Firebase project.
// It contains configuration for this Firebase app.
//
// If you change this file, you may break your app.
//
// To regenerate this file, run:
//   flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOSytoEvlGdCQXLSQrcl1PtIpsQ9Uxvws',
    appId: '1:831524396593:android:6a6c98951accf9c6883f10',
    messagingSenderId: '831524396593',
    projectId: 'trip-genie-8af8f',
    storageBucket: 'trip-genie-8af8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5L87RrVOrrRV4A4KtuJ0BfdP6b3fkVH4',
    appId: '1:831524396593:web:bff44613aa215185883f10',
    messagingSenderId: '831524396593',
    projectId: 'trip-genie-8af8f',
    authDomain: 'trip-genie-8af8f.firebaseapp.com',
    storageBucket: 'trip-genie-8af8f.firebasestorage.app',
    measurementId: 'G-SYLNDPJLC4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5L87RrVOrrRV4A4KtuJ0BfdP6b3fkVH4',
    appId: '1:831524396593:web:cd2c939cd2785350883f10',
    messagingSenderId: '831524396593',
    projectId: 'trip-genie-8af8f',
    authDomain: 'trip-genie-8af8f.firebaseapp.com',
    storageBucket: 'trip-genie-8af8f.firebasestorage.app',
    measurementId: 'G-LZWF3J8PF9',
  );

}